<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.5" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.16.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTOs\AppointmentDtos\" />
    <Folder Include="DTOs\BillingDtos\" />
    <Folder Include="DTOs\EmrDtos\" />
    <Folder Include="DTOs\LabTestDto\" />
    <Folder Include="DTOs\AppointmentDtos\PatientDtos\" />
    <Folder Include="DTOs\PatientDtos\" />
    <Folder Include="DTOs\TokenDtos\" />
    <Folder Include="Mapper\" />
    <Folder Include="Repositories\AppointmentRepository\" />
    <Folder Include="Repositories\AuditRepo\" />
    <Folder Include="Repositories\BillingRepo\" />
    <Folder Include="Repositories\LabTestRepository\" />
    <Folder Include="Repositories\PatientRepo\" />
    <Folder Include="Repositories\TokenRepo\" />
    <Folder Include="Services\AppointmentServices\" />
    <Folder Include="Services\AuthServices\" />
    <Folder Include="Services\LabTestServices\" />
    <Folder Include="Repositories\PrescriptionRepo\" />
    <Folder Include="Services\EmrServices\" />
    <Folder Include="Services\PrescriptionServices\" />
    <Folder Include="Services\PatientServices\" />
    <Folder Include="Utilities\Exceptions\" />
    <Folder Include="Utilities\Helpers\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MediCore.Domain\MediCore.Domain.csproj" />
  </ItemGroup>

</Project>
