// <auto-generated />
using System;
using MediCore.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediCore.Api.Migrations
{
    [DbContext(typeof(MediCoreDbContext))]
    partial class MediCoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MediCore.Domain.Entities.Appointment", b =>
                {
                    b.Property<int>("AppointmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentID"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DoctorID")
                        .HasColumnType("int");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time");

                    b.HasKey("AppointmentID");

                    b.HasIndex("DoctorID");

                    b.HasIndex("PatientID");

                    b.ToTable("Appointment");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.Bill", b =>
                {
                    b.Property<int>("BillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BillID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<int?>("PatientID1")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("BillID");

                    b.HasIndex("PatientID");

                    b.HasIndex("PatientID1");

                    b.ToTable("Bill");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.BillItem", b =>
                {
                    b.Property<int>("BillItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BillItemID"));

                    b.Property<int>("BillID")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BillItemID");

                    b.HasIndex("BillID");

                    b.ToTable("BillItems");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.ComplianceRecord", b =>
                {
                    b.Property<int>("ComplianceRecordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComplianceRecordID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NurseID")
                        .HasColumnType("int");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ComplianceRecordID");

                    b.HasIndex("NurseID");

                    b.HasIndex("PatientID");

                    b.ToTable("ComplianceRecord");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.Dispense", b =>
                {
                    b.Property<int>("DispenseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DispenseID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PharmacistID")
                        .HasColumnType("int");

                    b.Property<int>("PrescriptionID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("DispenseID");

                    b.HasIndex("PharmacistID");

                    b.HasIndex("PrescriptionID");

                    b.ToTable("Dispense");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.Doctor", b =>
                {
                    b.Property<int>("DoctorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorID"));

                    b.Property<DateOnly>("DOB")
                        .HasColumnType("date");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Speciality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("DoctorID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Doctor");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.EMR", b =>
                {
                    b.Property<int>("EMRID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EMRID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorID")
                        .HasColumnType("int");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("TreatmentPlan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EMRID");

                    b.HasIndex("DoctorID");

                    b.HasIndex("PatientID");

                    b.ToTable("EMR");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.FinanceOfficer", b =>
                {
                    b.Property<int>("FinanceOfficerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FinanceOfficerID"));

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("FinanceOfficerID");

                    b.ToTable("FinanceOfficer");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.InsuranceClaim", b =>
                {
                    b.Property<int>("InsuranceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InsuranceID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BillID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("InsuranceID");

                    b.HasIndex("BillID");

                    b.HasIndex("UserID");

                    b.ToTable("InsuranceClaims");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.LabReport", b =>
                {
                    b.Property<int>("LabReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LabReportID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileURI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LabTestID")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("LabReportID");

                    b.HasIndex("LabTestID")
                        .IsUnique();

                    b.ToTable("LabReport");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.LabTest", b =>
                {
                    b.Property<int>("LabTestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LabTestID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorID")
                        .HasColumnType("int");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int?>("TechnicianID")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LabTestID");

                    b.HasIndex("DoctorID");

                    b.HasIndex("PatientID");

                    b.HasIndex("TechnicianID");

                    b.ToTable("LabTest");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.Medicine", b =>
                {
                    b.Property<int>("MedicineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicineID"));

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PharmacistID")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MedicineID");

                    b.HasIndex("PharmacistID");

                    b.ToTable("Medicine");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.Nurse", b =>
                {
                    b.Property<int>("NurseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NurseID"));

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("NurseID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Nurse");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.Patient", b =>
                {
                    b.Property<int>("PatientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DOB")
                        .HasColumnType("date");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int?>("InsuranceID")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("PatientID");

                    b.HasIndex("InsuranceID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Patient");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.PatientDocument", b =>
                {
                    b.Property<int>("PatientDocumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientDocumentID"));

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileURI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("VerificationStatus")
                        .HasColumnType("bit");

                    b.HasKey("PatientDocumentID");

                    b.HasIndex("PatientID");

                    b.ToTable("PatientDocument");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BillID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Method")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("PaymentID");

                    b.HasIndex("BillID");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.Pharmacist", b =>
                {
                    b.Property<int>("PharmacistID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PharmacistID"));

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("PharmacistID");

                    b.HasIndex("UserID");

                    b.ToTable("Pharmacist");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.Prescription", b =>
                {
                    b.Property<int>("PrescriptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrescriptionID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorID")
                        .HasColumnType("int");

                    b.Property<int>("EMRID")
                        .HasColumnType("int");

                    b.Property<int?>("PatientID")
                        .HasColumnType("int");

                    b.Property<int?>("PharmacistID")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("PrescriptionID");

                    b.HasIndex("DoctorID");

                    b.HasIndex("EMRID");

                    b.HasIndex("PatientID");

                    b.HasIndex("PharmacistID");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.PrescriptionItem", b =>
                {
                    b.Property<int>("PrescriptionItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrescriptionItemID"));

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Medicine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrescriptionID")
                        .HasColumnType("int");

                    b.HasKey("PrescriptionItemID");

                    b.HasIndex("PrescriptionID");

                    b.ToTable("PrescriptionItems");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.Schedule", b =>
                {
                    b.Property<int>("ScheduleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleID"));

                    b.Property<bool>("Availability")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DoctorID")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("TimeSlot")
                        .HasColumnType("time");

                    b.HasKey("ScheduleID");

                    b.HasIndex("DoctorID");

                    b.ToTable("Schedule");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.Technician", b =>
                {
                    b.Property<int>("TechnicianID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TechnicianID"));

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("TechnicianID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Technician");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.TreatmentLog", b =>
                {
                    b.Property<int>("TreatmentLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TreatmentLogID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("EMRID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NurseID")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("TreatmentLogID");

                    b.HasIndex("EMRID");

                    b.HasIndex("NurseID");

                    b.ToTable("TreatmentLog");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("RoleName")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("UserID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("MediCore.Domain.Entities.Doctor", "DoctorIDNavigator")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediCore.Domain.Entities.Patient", "PatientIDNavigator")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DoctorIDNavigator");

                    b.Navigation("PatientIDNavigator");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.Bill", b =>
                {
                    b.HasOne("MediCore.Domain.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediCore.Domain.Entities.Patient", null)
                        .WithMany("Bills")
                        .HasForeignKey("PatientID1");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.BillItem", b =>
                {
                    b.HasOne("MediCore.Domain.Entities.Bill", "Bill")
                        .WithMany("BillItems")
                        .HasForeignKey("BillID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.ComplianceRecord", b =>
                {
                    b.HasOne("MediCore.Domain.Entities.Nurse", null)
                        .WithMany("ComplianceRecords")
                        .HasForeignKey("NurseID");

                    b.HasOne("MediCore.Domain.Entities.Patient", "PatientIDNavigator")
                        .WithMany("ComplianceRecords")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatientIDNavigator");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.Dispense", b =>
                {
                    b.HasOne("MediCore.Domain.Entities.Pharmacist", "PharmacistIDNavigator")
                        .WithMany("Dispenses")
                        .HasForeignKey("PharmacistID");

                    b.HasOne("MediCore.Domain.Entities.Prescription", "PrescriptionIDNavigator")
                        .WithMany()
                        .HasForeignKey("PrescriptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PharmacistIDNavigator");

                    b.Navigation("PrescriptionIDNavigator");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.Doctor", b =>
                {
                    b.HasOne("MediCore.Domain.Entities.User", "UserIDNavigator")
                        .WithOne("Doctor")
                        .HasForeignKey("MediCore.Domain.Entities.Doctor", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserIDNavigator");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.EMR", b =>
                {
                    b.HasOne("MediCore.Domain.Entities.Doctor", "DoctorIDNavigator")
                        .WithMany("EMRs")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediCore.Domain.Entities.Patient", "PatientIDNavigator")
                        .WithMany("EMRs")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoctorIDNavigator");

                    b.Navigation("PatientIDNavigator");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.InsuranceClaim", b =>
                {
                    b.HasOne("MediCore.Domain.Entities.Bill", "Bill")
                        .WithMany()
                        .HasForeignKey("BillID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediCore.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.LabReport", b =>
                {
                    b.HasOne("MediCore.Domain.Entities.LabTest", "LabTestIDNavigator")
                        .WithOne("LabReport")
                        .HasForeignKey("MediCore.Domain.Entities.LabReport", "LabTestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LabTestIDNavigator");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.LabTest", b =>
                {
                    b.HasOne("MediCore.Domain.Entities.Doctor", "DoctorIDNavigator")
                        .WithMany("LabTests")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediCore.Domain.Entities.Patient", "PatientIDNavigator")
                        .WithMany("LabTests")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediCore.Domain.Entities.Technician", "TechnicianIDNavigator")
                        .WithMany("LabTests")
                        .HasForeignKey("TechnicianID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DoctorIDNavigator");

                    b.Navigation("PatientIDNavigator");

                    b.Navigation("TechnicianIDNavigator");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.Medicine", b =>
                {
                    b.HasOne("MediCore.Domain.Entities.Pharmacist", null)
                        .WithMany("Medicines")
                        .HasForeignKey("PharmacistID");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.Nurse", b =>
                {
                    b.HasOne("MediCore.Domain.Entities.User", "UserIDNavigator")
                        .WithOne("Nurse")
                        .HasForeignKey("MediCore.Domain.Entities.Nurse", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserIDNavigator");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.Patient", b =>
                {
                    b.HasOne("MediCore.Domain.Entities.InsuranceClaim", "InsuranceIDNavigator")
                        .WithMany()
                        .HasForeignKey("InsuranceID");

                    b.HasOne("MediCore.Domain.Entities.User", "UserIDNavigator")
                        .WithOne("Patient")
                        .HasForeignKey("MediCore.Domain.Entities.Patient", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InsuranceIDNavigator");

                    b.Navigation("UserIDNavigator");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.PatientDocument", b =>
                {
                    b.HasOne("MediCore.Domain.Entities.Patient", "PatientIDNavigator")
                        .WithMany("PatientDocuments")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatientIDNavigator");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.Payment", b =>
                {
                    b.HasOne("MediCore.Domain.Entities.Bill", "BillIDNaviagator")
                        .WithMany()
                        .HasForeignKey("BillID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillIDNaviagator");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.Pharmacist", b =>
                {
                    b.HasOne("MediCore.Domain.Entities.User", "UserIDNavigator")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserIDNavigator");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.Prescription", b =>
                {
                    b.HasOne("MediCore.Domain.Entities.Doctor", "DoctorIDNavigator")
                        .WithMany("Prescriptions")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediCore.Domain.Entities.EMR", "EMRIDNavigator")
                        .WithMany("Prescriptions")
                        .HasForeignKey("EMRID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediCore.Domain.Entities.Patient", null)
                        .WithMany("Prescriptions")
                        .HasForeignKey("PatientID");

                    b.HasOne("MediCore.Domain.Entities.Pharmacist", null)
                        .WithMany("Prescriptions")
                        .HasForeignKey("PharmacistID");

                    b.Navigation("DoctorIDNavigator");

                    b.Navigation("EMRIDNavigator");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.PrescriptionItem", b =>
                {
                    b.HasOne("MediCore.Domain.Entities.Prescription", "Prescription")
                        .WithMany("PrescriptionItems")
                        .HasForeignKey("PrescriptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.Schedule", b =>
                {
                    b.HasOne("MediCore.Domain.Entities.Doctor", "DoctorIDNavigator")
                        .WithMany("Schedules")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoctorIDNavigator");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.Technician", b =>
                {
                    b.HasOne("MediCore.Domain.Entities.User", "UserIDNavigator")
                        .WithOne("Technician")
                        .HasForeignKey("MediCore.Domain.Entities.Technician", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserIDNavigator");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.TreatmentLog", b =>
                {
                    b.HasOne("MediCore.Domain.Entities.EMR", "EMRIDNavigator")
                        .WithMany()
                        .HasForeignKey("EMRID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediCore.Domain.Entities.Nurse", "NurseIDNavigator")
                        .WithMany()
                        .HasForeignKey("NurseID");

                    b.Navigation("EMRIDNavigator");

                    b.Navigation("NurseIDNavigator");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.Bill", b =>
                {
                    b.Navigation("BillItems");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("EMRs");

                    b.Navigation("LabTests");

                    b.Navigation("Prescriptions");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.EMR", b =>
                {
                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.LabTest", b =>
                {
                    b.Navigation("LabReport");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.Nurse", b =>
                {
                    b.Navigation("ComplianceRecords");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Bills");

                    b.Navigation("ComplianceRecords");

                    b.Navigation("EMRs");

                    b.Navigation("LabTests");

                    b.Navigation("PatientDocuments");

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.Pharmacist", b =>
                {
                    b.Navigation("Dispenses");

                    b.Navigation("Medicines");

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.Prescription", b =>
                {
                    b.Navigation("PrescriptionItems");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.Technician", b =>
                {
                    b.Navigation("LabTests");
                });

            modelBuilder.Entity("MediCore.Domain.Entities.User", b =>
                {
                    b.Navigation("Doctor");

                    b.Navigation("Nurse");

                    b.Navigation("Patient");

                    b.Navigation("Technician");
                });
#pragma warning restore 612, 618
        }
    }
}
